In [251]:
answer = []
matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix = [[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]]
matrix = [[2,3,4],[5,6,7],[8,9,10],[11,12,13],[14,15,16]]

print(np.array(matrix))

m, n = len(matrix), len(matrix[0])
while True:
  
  for i in range(len(matrix[0])):
    answer.append(matrix[0][0])
    matrix[0].pop(0)
  matrix.pop(0)

  if len(answer) == m * n:
    break

  for j in range(len(matrix) - 1):
    answer.append(matrix[j][-1])
    matrix[j].pop(-1)
  
  if len(answer) == m * n:
    break

  for k in range(len(matrix[-1])):
    answer.append(matrix[-1][-1])
    matrix[-1].pop(-1)
  matrix.pop(-1)

  if len(answer) == m * n:
    break

  for l in reversed(range(len(matrix))):
    answer.append(matrix[l][0])
    matrix[l].pop(0)

  if len(answer) == m * n:
    break


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [253]:
answer

[2, 3, 4, 7, 10, 13, 16, 15, 14, 11, 8, 5, 6, 9, 12]

In [254]:
class Solution(object):
    def spiralOrder(self, matrix):
        """
        :type matrix: List[List[int]]
        :rtype: List[int]
        """
        answer = []
        
        m = len(matrix)
        n = len(matrix[0])

        m, n = len(matrix), len(matrix[0])
        while True:
  
            for i in range(len(matrix[0])):
                answer.append(matrix[0][0])
                matrix[0].pop(0)
            matrix.pop(0)

            if len(answer) == m * n:
                break

            for j in range(len(matrix) - 1):
                answer.append(matrix[j][-1])
                matrix[j].pop(-1)
  
            if len(answer) == m * n:
                break

            for k in range(len(matrix[-1])):
                answer.append(matrix[-1][-1])
                matrix[-1].pop(-1)
            matrix.pop(-1)

            if len(answer) == m * n:
                break

            for l in reversed(range(len(matrix))):
                answer.append(matrix[l][0])
                matrix[l].pop(0)

            if len(answer) == m * n:
                break
        return answer

In [261]:
matrix = [[2,3,4],[5,6,7],[8,9,10],[11,12,13],[14,15,16]]
Cls = Solution()
print(Cls.spiralOrder(matrix))

[2, 3, 4, 7, 10, 13, 16, 15, 14, 11, 8, 5, 6, 9, 12]
